import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import { AppProvider } from "./context/AppContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <div className="flex flex-col lg:flex-row min-h-screen bg-gray-50">
            <aside className="lg:w-64 ">
              <Sidebar />
            </aside>

            <main className="flex-1 w-full min-h-screen lg:pt-0 overflow-x-hidden">
              <div className=" sm:p-6 lg:p-8">{children}</div>
            </main>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
